CREATE TABLE IF NOT EXISTS  moeda (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  codigo VARCHAR(3) NOT NULL,
  numero int,
  descricao VARCHAR(250) NOT NULL
);

insert into moeda(codigo, numero, descricao) values ( 'AFN',	971,  'Afegane');
insert into moeda(codigo, numero, descricao) values ( 'ALL',	8,  'Lek');
insert into moeda(codigo, numero, descricao) values ( 'AOA',	973,  'Kwanza');
insert into moeda(codigo, numero, descricao) values ( 'XCD',	951,  'Dólar das Caraíbas Orientais');
insert into moeda(codigo, numero, descricao) values ( 'ANG',	532,  'Florim');
insert into moeda(codigo, numero, descricao) values ( 'SAR',	682,  'Riyal');
insert into moeda(codigo, numero, descricao) values ( 'DZD',	12,  'Dinar argelino');
insert into moeda(codigo, numero, descricao) values ( 'ARS',	32,  'Peso Argentino');
insert into moeda(codigo, numero, descricao) values ( 'AMD',	51,  'Dram');
insert into moeda(codigo, numero, descricao) values ( 'AWG',	533,  'Florim de Aruba');
insert into moeda(codigo, numero, descricao) values ( 'AUD',	36,  'Dólar australiano');
insert into moeda(codigo, numero, descricao) values ( 'AZN',	944,  'Manat do Azerbaijão');
insert into moeda(codigo, numero, descricao) values ( 'BSD',	44,  'Dólar das Bahamas');
insert into moeda(codigo, numero, descricao) values ( 'BHD',	48,  'Dinar do Bahrein');
insert into moeda(codigo, numero, descricao) values ( 'BDT',	50,  'Taka');
insert into moeda(codigo, numero, descricao) values ( 'BBD',	52,  'Dólar de Barbados');
insert into moeda(codigo, numero, descricao) values ( 'BZD',	84,  'Dólar do Belize');
insert into moeda(codigo, numero, descricao) values ( 'XOF',	952,  'Franco CFA ocidental');
insert into moeda(codigo, numero, descricao) values ( 'BMD',	60,  'Dólar bermudense');
insert into moeda(codigo, numero, descricao) values ( 'BYR',	974,  'Rublo bielorrusso');
insert into moeda(codigo, numero, descricao) values ( 'BOB',	68,  'Boliviano');
insert into moeda(codigo, numero, descricao) values ( 'BOV',	984,  'Boliviano Mvdol');
insert into moeda(codigo, numero, descricao) values ( 'BAM',	977,  'Marco convertível');
insert into moeda(codigo, numero, descricao) values ( 'BWP',	72,  'Pula');
insert into moeda(codigo, numero, descricao) values ( 'BRL',	986,  'Real');
insert into moeda(codigo, numero, descricao) values ( 'BND',	96,  'Dólar do Brunei');
insert into moeda(codigo, numero, descricao) values ( 'BGN',	975,  'Lev búlgaro');
insert into moeda(codigo, numero, descricao) values ( 'BIF',	108,  'Franco do Burundi');
insert into moeda(codigo, numero, descricao) values ( 'BTN',	64,  'Ngultrum');
insert into moeda(codigo, numero, descricao) values ( 'CVE',	132,  'Escudo cabo-verdiano');
insert into moeda(codigo, numero, descricao) values ( 'XAF',	950,  'Franco CFA central');
insert into moeda(codigo, numero, descricao) values ( 'KHR',	116,  'Riel');
insert into moeda(codigo, numero, descricao) values ( 'CAD',	124,  'Dólar canadense');
insert into moeda(codigo, numero, descricao) values ( 'QAR',	634,  'Rial do Qatar');
insert into moeda(codigo, numero, descricao) values ( 'KZT',	398,  'Tenge');
insert into moeda(codigo, numero, descricao) values ( 'CZK',	203,  'Coroa checa');
insert into moeda(codigo, numero, descricao) values ( 'CLP',	152,  'Peso chileno');
insert into moeda(codigo, numero, descricao) values ( 'CNY',	156,  'Renminbi');
insert into moeda(codigo, numero, descricao) values ( 'COP',	170,  'Peso colombiano');
insert into moeda(codigo, numero, descricao) values ( 'COU',	970,  'Unidade de Valor Real');
insert into moeda(codigo, numero, descricao) values ( 'KMF',	174,  'Franco comoriano');
insert into moeda(codigo, numero, descricao) values ( 'KPW',	408,  'Won norte-coreano');
insert into moeda(codigo, numero, descricao) values ( 'KRW',	410,  'Won sul-coreano');
insert into moeda(codigo, numero, descricao) values ( 'CRC',	188,  'Colon da Costa Rica');
insert into moeda(codigo, numero, descricao) values ( 'HRK',	191,  'Kuna croata');
insert into moeda(codigo, numero, descricao) values ( 'CUC',	931,  'Peso cubano convertível');
insert into moeda(codigo, numero, descricao) values ( 'CUP',	192,  'Peso cubano');
insert into moeda(codigo, numero, descricao) values ( 'DKK',	208,  'Coroa dinamarquesa');
insert into moeda(codigo, numero, descricao) values ( 'DJF',	262,  'Franco do Djibouti');
insert into moeda(codigo, numero, descricao) values ( 'EGP',	818,  'Libra egípcia');
insert into moeda(codigo, numero, descricao) values ( 'SVC',	222,  'Colon de El Salvador');
insert into moeda(codigo, numero, descricao) values ( 'AED',	784,  'Dirham dos Emirados');
insert into moeda(codigo, numero, descricao) values ( 'ECS',	895,  'Sucre (O dólar americano USD é a moeda corrente no país)');
insert into moeda(codigo, numero, descricao) values ( 'ERN',	232,  'Nakfa');
insert into moeda(codigo, numero, descricao) values ( 'SZL',	748,  'Lilangeni');
insert into moeda(codigo, numero, descricao) values ( 'USD',	840,  'Dólar americano');
insert into moeda(codigo, numero, descricao) values ( 'ETB',	230,  'Birr etíope');
insert into moeda(codigo, numero, descricao) values ( 'FJD',	242,  'Dólar das Fiji');
insert into moeda(codigo, numero, descricao) values ( 'PHP',	608,  'Peso filipino');
insert into moeda(codigo, numero, descricao) values ( 'NPR',	524,  'Rupia nepalesa');
insert into moeda(codigo, numero, descricao) values ( 'SHP',	654,  'Libra de Santa Helena');
insert into moeda(codigo, numero, descricao) values ( 'GMD',	270,  'Dalasi');
insert into moeda(codigo, numero, descricao) values ( 'GHS',	936,  'Cedi');
insert into moeda(codigo, numero, descricao) values ( 'GEL',	981,  'Lari');
insert into moeda(codigo, numero, descricao) values ( 'GIP',	292,  'Libra de Gibraltar');
insert into moeda(codigo, numero, descricao) values ( 'GTQ',	320,  'Quetzal guatemalteco');
insert into moeda(codigo, numero, descricao) values ( 'GYD',	328,  'Dólar da Guiana');
insert into moeda(codigo, numero, descricao) values ( 'GNF',	324,  'Franco da Guiné');
insert into moeda(codigo, numero, descricao) values ( 'HTG',	332,  'Gourde');
insert into moeda(codigo, numero, descricao) values ( 'HNL',	340,  'Lempira');
insert into moeda(codigo, numero, descricao) values ( 'HKD',	344,  'Dólar de Hong Kong');
insert into moeda(codigo, numero, descricao) values ( 'HUF',	348,  'Forint');
insert into moeda(codigo, numero, descricao) values ( 'YER',	886,  'Rial iemenita');
insert into moeda(codigo, numero, descricao) values ( 'IMP', null, 'Libra manesa');
insert into moeda(codigo, numero, descricao) values ( 'KYD',	136,  'Dólar das Ilhas Cayman');
insert into moeda(codigo, numero, descricao) values ( 'FKP',	238,  'Libra das Malvinas');
insert into moeda(codigo, numero, descricao) values ( 'SBD',	90,   'Dólar das Ilhas Salomão');
insert into moeda(codigo, numero, descricao) values ( 'INR',	356,  'Rupia indiana');
insert into moeda(codigo, numero, descricao) values ( 'IDR',	360,  'Rupia indonésia');
insert into moeda(codigo, numero, descricao) values ( 'XDR',	960,  'Special Drawing Rights');
insert into moeda(codigo, numero, descricao) values ( 'IRR',	364,  'Rial iraniano');
insert into moeda(codigo, numero, descricao) values ( 'IQD',	368,  'Dinar iraquiano');
insert into moeda(codigo, numero, descricao) values ( 'ISK',	352,  'Coroa islandesa');
insert into moeda(codigo, numero, descricao) values ( 'ILS',	376,  'Shekel');
insert into moeda(codigo, numero, descricao) values ( 'EUR',	978,  'Euro');
insert into moeda(codigo, numero, descricao) values ( 'JMD',	388,  'Dólar jamaicano');
insert into moeda(codigo, numero, descricao) values ( 'JPY',	392,  'Iene');
insert into moeda(codigo, numero, descricao) values ( 'JOD',	400,  'Dinar jordano');
insert into moeda(codigo, numero, descricao) values ( 'KWD',	414,  'Dinar do Kuwait');
insert into moeda(codigo, numero, descricao) values ( 'LAK',	418,  'Kip');
insert into moeda(codigo, numero, descricao) values ( 'LSL',	426,  'Loti');
insert into moeda(codigo, numero, descricao) values ( 'ZAR',	710,  'Rand');
insert into moeda(codigo, numero, descricao) values ( 'LVL',	428,  'Lats');
insert into moeda(codigo, numero, descricao) values ( 'LBP',	422,  'Libra libanesa');
insert into moeda(codigo, numero, descricao) values ( 'LRD',	430,  'Dólar liberiano');
insert into moeda(codigo, numero, descricao) values ( 'LYD',	434,  'Dinar líbio');
insert into moeda(codigo, numero, descricao) values ( 'LTL',	440,  'Litas');
insert into moeda(codigo, numero, descricao) values ( 'MOP',	446,  'Pataca');
insert into moeda(codigo, numero, descricao) values ( 'MKD',	807,  'Denar');
insert into moeda(codigo, numero, descricao) values ( 'MGA',	969,  'Ariary');
insert into moeda(codigo, numero, descricao) values ( 'MYR',	458,  'Ringgit');
insert into moeda(codigo, numero, descricao) values ( 'MWK',	454,  'Kwacha');
insert into moeda(codigo, numero, descricao) values ( 'MVR',	462,  'Rufiyaa');
insert into moeda(codigo, numero, descricao) values ( 'MAD',	504,  'Dirham marroquino');
insert into moeda(codigo, numero, descricao) values ( 'MUR',	480,  'Rupia mauriciana');
insert into moeda(codigo, numero, descricao) values ( 'MRO',	478,  'Ouguiya');
insert into moeda(codigo, numero, descricao) values ( 'MXN',	484,  'Peso mexicano');
insert into moeda(codigo, numero, descricao) values ( 'MMK',	104,  'Kyat');
insert into moeda(codigo, numero, descricao) values ( 'MZN',	943,  'Metical');
insert into moeda(codigo, numero, descricao) values ( 'MDL',	498,  'Leu moldávio');
insert into moeda(codigo, numero, descricao) values ( 'MNT',	496,  'Tugrik');
insert into moeda(codigo, numero, descricao) values ( 'NAD',	516,  'Dólar da Namíbia');
insert into moeda(codigo, numero, descricao) values ( 'NIO',	558,  'Cordoba Oro');
insert into moeda(codigo, numero, descricao) values ( 'NGN',	566,  'Naira');
insert into moeda(codigo, numero, descricao) values ( 'NOK',	578,  'Coroa norueguesa');
insert into moeda(codigo, numero, descricao) values ( 'NZD',	554,  'Dólar da Nova Zelândia');
insert into moeda(codigo, numero, descricao) values ( 'OMR',	512,  'Rial Omani');
insert into moeda(codigo, numero, descricao) values ( 'PAB',	590,  'Balboa (O dólar americano USD é a moeda corrente no país)');
insert into moeda(codigo, numero, descricao) values ( 'PGK',	598,  'Kina');
insert into moeda(codigo, numero, descricao) values ( 'PKR',	586,  'Rupia paquistanesa');
insert into moeda(codigo, numero, descricao) values ( 'PYG',	600,  'Guarani');
insert into moeda(codigo, numero, descricao) values ( 'PEN',	604,  'Nuevo Sol');
insert into moeda(codigo, numero, descricao) values ( 'XPF',	953,  'Franco CFP');
insert into moeda(codigo, numero, descricao) values ( 'PLN',	985,  'Zloty');
insert into moeda(codigo, numero, descricao) values ( 'KES',	404,  'Xelim queniano');
insert into moeda(codigo, numero, descricao) values ( 'KGS',	417,  'Som');
insert into moeda(codigo, numero, descricao) values ( 'GBP',	826,  'Libra Esterlina');
insert into moeda(codigo, numero, descricao) values ( 'CDF',	976,  'Franco congolês');
insert into moeda(codigo, numero, descricao) values ( 'DOP',	214,  'Peso');
insert into moeda(codigo, numero, descricao) values ( 'RON',	946,  'Leu romeno');
insert into moeda(codigo, numero, descricao) values ( 'RWF',	646,  'Franco do Ruanda');
insert into moeda(codigo, numero, descricao) values ( 'RUB',	643,  'Rublo');
insert into moeda(codigo, numero, descricao) values ( 'WST',	882,  'Tala');
insert into moeda(codigo, numero, descricao) values ( 'STN',	930,  'Dobra');
insert into moeda(codigo, numero, descricao) values ( 'SCR',	690,  'Rupia das Seychelles');
insert into moeda(codigo, numero, descricao) values ( 'SLL',	694,  'Leone');
insert into moeda(codigo, numero, descricao) values ( 'RSD',	941,  'Dinar Sérvio');
insert into moeda(codigo, numero, descricao) values ( 'SGD',	702,  'Dólar de Singapura');
insert into moeda(codigo, numero, descricao) values ( 'SYP',	760,  'Libra da Síria');
insert into moeda(codigo, numero, descricao) values ( 'SOS',	706,  'Xelim somali');
insert into moeda(codigo, numero, descricao) values ( 'LKR',	144,  'Rupia do Sri Lanka');
insert into moeda(codigo, numero, descricao) values ( 'SDG',	938,  'Dinar sudanês');
insert into moeda(codigo, numero, descricao) values ( 'SEK',	752,  'Coroa Sueca');
insert into moeda(codigo, numero, descricao) values ( 'CHF',	756,  'Franco suíço');
insert into moeda(codigo, numero, descricao) values ( 'SRD',	968,  'Dólar do Suriname');
insert into moeda(codigo, numero, descricao) values ( 'THB',	764,  'Baht');
insert into moeda(codigo, numero, descricao) values ( 'TWD',	901,  'Novo dólar de Taiwan');
insert into moeda(codigo, numero, descricao) values ( 'TJS',	972,  'Somoni');
insert into moeda(codigo, numero, descricao) values ( 'TZS',	834,  'Xelim da Tanzânia');
insert into moeda(codigo, numero, descricao) values ( 'TOP',	776,  'Pa `anga');
insert into moeda(codigo, numero, descricao) values ( 'TTD',	780,  'Dólar de Trindade e Tobago');
insert into moeda(codigo, numero, descricao) values ( 'TND',	788,  'Dinar tunisino');
insert into moeda(codigo, numero, descricao) values ( 'TMT',	934,  'Manat turcomano');
insert into moeda(codigo, numero, descricao) values ( 'TRY',	949,  'Nova Lira turca');
insert into moeda(codigo, numero, descricao) values ( 'UAH',	980,  'Grívnia');
insert into moeda(codigo, numero, descricao) values ( 'UGX',	800,  'Xelim ugandês');
insert into moeda(codigo, numero, descricao) values ( 'UYU',	858,  'Peso uruguaio');
insert into moeda(codigo, numero, descricao) values ( 'UZS',	860,  'Som uzbeque');
insert into moeda(codigo, numero, descricao) values ( 'VUV',	548,  'Vatu');
insert into moeda(codigo, numero, descricao) values ( 'VES',	928,  'bolívar soberano venezuelano');
insert into moeda(codigo, numero, descricao) values ( 'VND',	704,  'Dong');
insert into moeda(codigo, numero, descricao) values ( 'ZMW',	894,  'Kwacha');
insert into moeda(codigo, numero, descricao) values ( 'ZWL',	932,  'Dólar zimbabuano');
